name: Birthday-reminder CI

env:
  CI: true
  SOUCE_LABS_USERNAME: ${{ secrets.SAUCE_LABS_USERNAME }}
  SOUCE_LABS_KEY: ${{ secrets.SAUCE_LABS_KEY }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        cd birthday-app/setup
        npm install & npm ci
    - name: Build the app
      run: |
        cd birthday-app/setup
        npm run build --if-present
    - name: Run componet tests
      run: |
        cd birthday-app/setup
        npm run test
    - name: Start the app
      run: |
        cd birthday-app/setup
        npm start & npx wait-on --timeout 60000
    - name: Run wdio tests
      run: |
        cd birthday-app/setup
        npm run wdio
